Mobile menu
Tommymarvel/Tommymarvel2.github.io pull request #2
Opened 2022-07-19 15:03 UTC by Tommymarvel

## Mobile menu

This PR content includes fantastic styling, well-written HTML, and javascript to add functions.

2022-07-19 22:53 UTC, tresorsawasawa requested changes
# STATUS: REQUIRED CHANGES :recycle::recycle: 

Hi @Tommymarvel :wave: 
Good job so far! I know you worked hard to implement this project, I really appreciate the effort you put in! But there are some issues that you still need to work on to go to the next project but you are almost there! 

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Your design looks good :100: :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Follow GitHub flow :heavy_check_mark: 

## Required changes :recycle: :recycle: 
- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-19 22:53 UTC, tresorsawasawa commented on index.html
>          <ul class="nav-tags">
- [ ] Kindly make sure your **Mobile Menu** design sticks to the one from your chosen Figma template as required for the project and then your project will be complete(e.g.: background color, blur effect on the background, font family, opacity,...). Check everything to match your design to the expected one.

| Figma Design | Your Design |
| ------------------- | ------------------- |
| ![mmf1](https://user-images.githubusercontent.com/83042742/179861251-29fe7a55-1ce0-458d-96d9-0081305ae2f6.png) | ![Screenshot from 2022-07-20 00-50-41](https://user-images.githubusercontent.com/83042742/179861507-998072de-2d48-441f-9981-a38455adb4b2.png) |

2022-07-20 09:50 UTC, vic778 approved these changes
Hi @Tommymarvel 
![Charlie Brown](https://media.giphy.com/media/ZdO4NenDbsQNwUwKDB/giphy.gif)

## Highlights

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification

2022-07-20 09:50 UTC, vic778 commented on index.html
> +            ></a>
- [OPTIONAL] Kindly the close-icon is not showing when the hamburger is pop-up. fix that and let's see your project get approved.
 
Your Design
![Screenshot from 2022-07-20 12-49-00](https://user-images.githubusercontent.com/77842237/179952971-5f5e84a6-84bc-4469-84ac-a54dd7928c75.png)

2022-07-20 09:59 UTC, merged